language: r
sudo: required
before_install:
- openssl aes-256-cbc -K $encrypted_e54876681f9b_key -iv $encrypted_e54876681f9b_iv
  -in .httr-oauth.enc -out tests/testthat/.httr-oauth -d
r_packages:
- uuid
r_github_packages:
- jimhester/covr
env:
- warnings_are_errors: false
after_success:
- Rscript -e 'library(covr); coveralls()'
