language: r
sudo: required
NOT_CRAN=true
before_install:
- openssl aes-256-cbc -K $encrypted_f287197b236c_key -iv $encrypted_f287197b236c_iv
  -in tests/testthat/.httr-oauth.enc -out tests/testthat/.httr-oauth -d
r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);coveralls()'  
env:
- warnings_are_errors: false
